### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by frediz** [libdfp/libdfp#3] opened 2015-03-31 07:00 UTC
On ppc64el, there a failure on test-strtod : 
$ cat test-strtod.out
104 Error:   Expected: "+0,000,000,000,000,000E-398"
             Result:   "+5,000,000,000,000,000E-398"
    in: ./tests/test-strtod.c:119.

Found 1 failures.

**Comment by tuliom** [comment] 2015-04-06 17:47
I was able to reproduce this issue on Ubuntu 14.04.

**Comment by tuliom** [comment] 2015-04-17 14:08
@frediz It looks like Debian and Ubuntu are building libdfp without support for hardware decimal floating point.
I strongly recommend to either update them to commit ID 167c95fc or/and start configuring it with --with-cpu.

This error is happening on soft-dfp only.

**Comment by pmur** [comment] 2015-09-24 22:11
This is fixed by commit 81e81749bde01845c4866d775eb8fbb3b69b6495 on master.

**Closed by pmur** 2015-09-24 22:11 UTC
Labels: bug
