### ISSUE TITLE
_Decimal64 * 1000 may give wrong results

### ISSUE THREAD

**Issue by jmdubois** [libdfp/libdfp#49] opened 2016-05-28 17:35 UTC
O.S. : Centos7 64 bits
GCC : 4.9.3
libdfp: master

```
#define __STDC_WANT_DEC_FP__

#include <math.h>
#include <fenv.h>
#include <stdlib.h>
#include <wchar.h>
#include <stdio.h>

main()
{
        _Decimal64 a = 9.853946746503084DD;
        printf("%Da * 1000 = %Da\n", a, a * 1000.0DD);
        return 0;
}

```
result :  

9.853946746503084 * 1000 = 98539467.46503084

**Comment by tuliom** [comment] 2016-05-30 23:11
I couldn't reproduce this on ppc64le.
@jmdubois which architecture did you use?

**Comment by jmdubois** [comment] 2016-05-31 07:27
I use a CentOS 7 64 bits in a VMWare Workstation virtual machine runing in a Core i7 computer.

**Comment by pmur** [comment] 2016-05-31 15:36
I confirmed this bug happens under -O0. The conversion back to BID from libdecnumber is wrong within libdfp's __bid_muldd3.

**Comment by jmdubois** [comment] 2016-05-31 16:29
The result is wrong with 'CFLAGS=-O2;./configure' also.

**Comment by pmur** [comment] 2016-06-06 22:19
This should be fixed upstream now. Thank you for reporting @jmdubois

**Closed by pmur** 2016-06-06 22:19 UTC
